Repository AnswerDotAI/nbdev, pull requests merged in 2022-11, with the labels that each got.

#1202 utility that creates a `requirements.txt` file from `settings.ini`
  nbdev/_modidx.py
  nbdev/release.py
  nbs/api/release.ipynb
Labels: enhancement

#1204 add parameter for name to nb_export
  nbdev/export.py
  nbs/api/export.ipynb
Labels: enhancement

#1205 HF spaces blog post
  nbs/blog/posts/2022-11-07-spaces/app.py
  nbs/blog/posts/2022-11-07-spaces/blog_cover.jpeg
  nbs/blog/posts/2022-11-07-spaces/create_space.png
  nbs/blog/posts/2022-11-07-spaces/final_app.png
  nbs/blog/posts/2022-11-07-spaces/gradio_local.png
  nbs/blog/posts/2022-11-07-spaces/index.qmd
  nbs/styles.css
Labels: documentation

#1214 make anaconda description links consistent with pypi
  nbdev/release.py
  nbs/api/release.ipynb
Labels: bug

#1221 fix order of categories for migration
  nbdev/migrate.py
  nbs/api/migrate.ipynb
Labels: bug
