Repository AnswerDotAI/nbdev, pull requests merged in 2022-08, with the labels that each got.

#706 only add to `.gitattributes` if missing
  nbdev/clean.py
  nbs/11_clean.ipynb
Labels: bug

#730 fix `nbdev_test` with no `--fname` in non-nbdev repos
  nbdev/_modidx.py
  nbdev/doclinks.py
  nbs/04b_doclinks.ipynb
Labels: bug

#737 fix `nbdev_merge` during rebase; fix `nbdev_fix` `nobackup` default
  nbdev/merge.py
  nbs/06_merge.ipynb
  nbs/11_clean.ipynb
Labels: bug

#738 add `user` option to `jupyter_hooks` setting
  nbdev/clean.py
  nbs/11_clean.ipynb
Labels: enhancement

#763 add `show_src` to display rich source code
  nbdev/_modidx.py
  nbdev/maker.py
  nbdev/read.py
  nbs/01_read.ipynb
  nbs/02_maker.ipynb
Labels: enhancement

#768 `get_config` works without a settings file
  nbdev/_modidx.py
  nbdev/read.py
  nbs/01_read.ipynb
Labels: enhancement

#770 use global defaults instead of respecifying each time
  nbdev/clean.py
  nbdev/cli.py
  nbdev/doclinks.py
  nbdev/migrate.py
  nbdev/test.py
  nbs/04b_doclinks.ipynb
  nbs/10_cli.ipynb
  nbs/11_clean.ipynb
  nbs/14_test.ipynb
  nbs/15_migrate.ipynb
Labels: enhancement

#774 fix #773
  nbdev/maker.py
  nbs/02_maker.ipynb
Labels: bug

#778 Allow users to provide user-level settings in ~/.config/nbdev/settings.ini
  nbdev/_modidx.py
  nbdev/read.py
  nbs/01_read.ipynb
Labels: enhancement

#780 Simplify `jupyter_hooks` configuration
  nbdev/_modidx.py
  nbdev/clean.py
  nbdev/read.py
  nbs/01_read.ipynb
  nbs/11_clean.ipynb
  settings.ini
Labels: enhancement

#781 Fix directive migration when there is no test flag
  nbdev/migrate.py
  nbs/15_migrate.ipynb
Labels: bug

#782 Allow for dash in Quarto directives
  nbdev/process.py
  nbs/03_process.ipynb
Labels: bug

#783 Migrate collapsible code cell directives
  nbdev/migrate.py
  nbs/15_migrate.ipynb
Labels: enhancement

#784 Hooks ignore settings.ini if Jupyter is started outside nbdev repo
  nbdev/clean.py
  nbs/11_clean.ipynb
Labels: bug

#787 `nbdev_merge` fails on `git stash pop` conflict
  nbdev/merge.py
  nbs/06_merge.ipynb
Labels: bug

#794 `clean_ids` corrupts string outputs
  nbdev/clean.py
  nbs/11_clean.ipynb
Labels: bug

#795 links aren't rendered as code
  nbdev/doclinks.py
  nbs/04b_doclinks.ipynb
  nbs/09_processors.ipynb
Labels: bug

#798 tutorial: git friendly jupyter
  nbs/11_clean.ipynb
  nbs/17_release.ipynb
  nbs/git_friendly_jupyter.ipynb
  nbs/images/jupyter-friendly-conflict.png
  nbs/images/jupyter-unreadable-notebook.png
  nbs/sidebar.yml
Labels: documentation

#812 refactor tutorial intro and installation
  nbdev/tutorial.py
  nbs/images/jupyter-blank-terminal.png
  nbs/images/jupyter-home-page.png
  nbs/tutorial.ipynb
Labels: documentation

#813 nbdev commands fail when `doc_path` contains whitespace
  nbdev/cli.py
  nbs/10_cli.ipynb
Labels: bug

#820 Streamline `nbdev_new`: outputs are now in color, you can pass `--lib_name`, and it calls `nbdev_export`
  nbdev/cli.py
  nbs/10_cli.ipynb
Labels: enhancement

#829 refactor tutorial: first steps
  nbdev/tutorial.py
  nbs/images/bom.png
  nbs/images/github-actions-initial.png
  nbs/images/github-actions-pages.png
  nbs/images/github-create-new-repo.png
  nbs/images/github-enable-pages.png
  nbs/images/github-repo-empty.png
  nbs/images/jupyter-blank-terminal.png
  nbs/images/jupyter-home-page.png
  nbs/images/jupyter-unreadable-notebook.png
  nbs/images/nbdev-hello-world-site-initial.png
  nbs/images/token.png
  nbs/tutorial.ipynb
Labels: documentation

#836 refactor tutorial: make your first edit
  nbdev/tutorial.py
  nbs/tutorial.ipynb
Labels: documentation

#842 Add custom_quarto_yml setting
  nbdev/cli.py
  nbs/10_cli.ipynb
Labels: enhancement

#855 fix `show_doc` signature whitespace removal
  nbdev/showdoc.py
  nbs/08_showdoc.ipynb
Labels: bug

#856 deprecate `config_key` in favor of `get_config`
  nbdev/_modidx.py
  nbdev/clean.py
  nbdev/cli.py
  nbdev/doclinks.py
  nbdev/migrate.py
  nbdev/read.py
  nbdev/release.py
  nbdev/test.py
  nbs/01_read.ipynb
  nbs/04b_doclinks.ipynb
  nbs/10_cli.ipynb
  nbs/11_clean.ipynb
  nbs/14_test.ipynb
  nbs/15_migrate.ipynb
  nbs/17_release.ipynb
  settings.ini
Labels: enhancement

#861 fix overflowing `release` demo svg
  nbs/17_release.ipynb
Labels: documentation

#864 Improve config documentation in `read` module
  nbdev/read.py
  nbs/01_read.ipynb
  nbs/styles.css
Labels: enhancement

#866 `nbdev_new` renders notebooks with information from your config file
  nbdev/cli.py
  nbdev/maker.py
  nbdev/showdoc.py
  nbs/02_maker.ipynb
  nbs/08_showdoc.ipynb
  nbs/12_cli.ipynb
  nbs/images/nbdev-hello-world-site-initial.png
Labels: enhancement

#878 improvements to `nbdev_new` and `nbdev_create_config`
  nbdev/_modidx.py
  nbdev/cli.py
  nbdev/config.py
  nbs/01_config.ipynb
  nbs/12_cli.ipynb
Labels: enhancement, breaking

#868 Document all of the directives
  nbs/explanations/directives.ipynb
  nbs/explanations/showdoc.ipynb
  nbs/sidebar.yml
Labels: documentation

#905 allow nbdev directives to work with cell magic
  nbdev/process.py
  nbs/03_process.ipynb
Labels: bug

#906 Make sure `#|exec_doc` triggers an update even when there is no export or show_doc
  nbdev/processors.py
  nbs/09b_processors.ipynb
Labels: bug

#917 add tutorial alias
  nbs/01_Tutorials/tutorial.ipynb
Labels: bug

#918 fix images
  nbs/01_Tutorials/images/jupyter-friendly-conflict.png
  nbs/01_Tutorials/images/jupyter-unreadable-notebook.png
Labels: bug

#919 run `nbdev_readme` in `nbdev_new`
  nbdev/cli.py
  nbdev/config.py
  nbs/01_config.ipynb
  nbs/12_cli.ipynb
Labels: enhancement

#921 Improve the "Make your first edit" section of the walkthrough
  nbdev/tutorial.py
  nbs/01_Tutorials/01_tutorial.ipynb
  nbs/01_Tutorials/02_git_friendly_jupyter.ipynb
  nbs/custom.yml
  nbs/sidebar.yml
Labels: enhancement

#931 add `printit` arg to `nbdev_filter` so it can be called with `fname` and still print to stdout
  README.md
  nbdev/cli.py
  nbs/12_cli.ipynb
Labels: enhancement

#934 Correct cell index in `nbdev_update`
  nbdev/sync.py
  nbs/05_sync.ipynb
Labels: bug

#930 Handle repo names with dashes and correct index page rendering with file attachments
  nbdev/config.py
  nbdev/quarto.py
  nbs/01_config.ipynb
  nbs/13_quarto.ipynb
Labels: bug

#950 Misc docs improvements
  README.md
  nbs/01_Tutorials/03_modular_nbdev.ipynb
  nbs/02_Explanations/config.ipynb
  nbs/getting_started.ipynb
  nbs/styles.css
Labels: documentation

#955 setup GitHub repo automatically
  nbdev/_modidx.py
  nbdev/cli.py
  nbs/09_API/12_cli.ipynb
Labels: enhancement

#959 Experimental: pre-commit hooks
  .pre-commit-hooks.yaml
Labels: enhancement

#962 update tutorial "Check out your docs" section re:pages enablement
  nbs/01_Tutorials/01_tutorial.ipynb
Labels: documentation
