Repository AnswerDotAI/nbdev, pull requests merged in 2022-09, with the labels that each got.

#974 add docs explanation section
  nbs/01_Tutorials/01_tutorial.ipynb
  nbs/02_Explanations/directives.ipynb
  nbs/02_Explanations/docs.ipynb
  nbs/02_Explanations/images/github-actions-pages.png
  nbs/02_Explanations/showdoc.ipynb
Labels: documentation

#988 Modify docs explainer for new nbdev "filter"
  nbs/Explanations/docs.ipynb
Labels: documentation

#1022 fix links
  nbs/Tutorials/best_practices.ipynb
  nbs/api/images/release.svg
  nbs/api/images/token.png
  nbs/getting_started.ipynb
Labels: documentation

#1024 fix: `nbdev.release` uses `cfg.lib_name` instead of `cfg.repo`
  nbdev/release.py
  nbs/api/release.ipynb
  settings.ini
Labels: bug

#1029 restructure best practices
  nbs/tutorials/best_practices.ipynb
Labels: documentation

#1030 edit best practices intro
  nbs/tutorials/best_practices.ipynb
Labels: documentation

#1028 suppress `UserWarning` for unset `GITHUB_TOKEN` in `nbdev_new`
  nbdev/cli.py
  nbs/api/cli.ipynb
Labels: bug

#1036 edit best practices
  nbs/tutorials/best_practices.ipynb
Labels: documentation

#1037 fix card overflow css
  nbs/explanations/docs.ipynb
  nbs/tutorials/best_practices.ipynb
Labels: documentation

#1043 `nbdev_new` support for GitHub Enterprise
  nbdev/cli.py
  nbs/api/cli.ipynb
  settings.ini
Labels: enhancement

#1044 Tutorial "Pre-commit hooks"
  nbdev/_modidx.py
  nbdev/qmd.py
  nbs/api/qmd.ipynb
  nbs/tutorials/git_friendly_jupyter.ipynb
  nbs/tutorials/modular_nbdev.ipynb
  nbs/tutorials/pre_commit.ipynb
  nbs/tutorials/tutorial.ipynb
Labels: documentation

#1045 fix typo in pre-commit tutorial
  nbs/tutorials/pre_commit.ipynb
Labels: documentation

#1046 class method doclinks target `mod.html#method` instead of `mod.html#class.method`
  nbdev/_modidx.py
  nbdev/doclinks.py
  nbs/api/doclinks.ipynb
Labels: bug

#1048 fix tutorial preview card
  nbs/tutorials/tutorial.ipynb
Labels: documentation

#1049 fix #1041
  nbdev/_modidx.py
  nbdev/clean.py
  nbdev/config.py
  nbs/api/clean.ipynb
  nbs/api/config.ipynb
  settings.ini
Labels: bug

#1062 use migration commands that work with default macos shell
  nbs/migrating.ipynb
Labels: documentation

#1061 Add Blog Tutorial
  README.md
  nbs/_quarto.yml
  nbs/api/migrate.ipynb
  nbs/blog/index.qmd
  nbs/blog/posts/2022-07-28-nbdev2/index.qmd
  nbs/blog/posts/2022-07-28-nbdev2/lang_rank.png
  nbs/blog/posts/2022-07-28-nbdev2/logo_lyft.png
  nbs/blog/posts/2022-07-28-nbdev2/logo_netflix.png
  nbs/blog/posts/2022-07-28-nbdev2/logo_ob.png
  nbs/blog/posts/2022-07-28-nbdev2/logo_transform.png
  nbs/blog/posts/2022-07-28-nbdev2/nb_quarto.png
  nbs/blog/posts/2022-07-28-nbdev2/patch.png
  nbs/blog/posts/2022-08-25-jupyter-git/friendly-conflict.png
  nbs/blog/posts/2022-08-25-jupyter-git/index.qmd
  nbs/blog/posts/2022-08-25-jupyter-git/unreadable-notebook.png
  nbs/getting_started.ipynb
  nbs/migrating.ipynb
  nbs/styles.css
  nbs/tutorials/best_practices.ipynb
  nbs/tutorials/blogging.ipynb
  nbs/tutorials/git_friendly_jupyter.ipynb
  nbs/tutorials/modular_nbdev.ipynb
  nbs/tutorials/pre_commit.ipynb
  nbs/tutorials/qmd_intro.qmd
  nbs/tutorials/tutorial.ipynb
Labels: enhancement

#1075 fix alias bug
  nbdev/migrate.py
  nbs/api/migrate.ipynb
  tests/2022-09-06-homeschooling.md
Labels: bug

#1078 improve jekyll migration
  nbdev/migrate.py
  nbs/api/migrate.ipynb
  tests/2022-09-06-homeschooling.md
Labels: bug

#1079 respect `#|hide` and `#|include: false` for showdoc
  nbdev/processors.py
  nbs/api/processors.ipynb
Labels: bug

#1090 restructure "Notebook best practices" tutorial
  nbs/explanations/docs.ipynb
  nbs/explanations/why_nbdev.ipynb
  nbs/tutorials/best_practices.ipynb
  nbs/tutorials/images/marie-curie-notebook.jpg
Labels: documentation

#1095 use `...` instead of `pass`
  nbs/tutorials/best_practices.ipynb
Labels: documentation

#1100 fix exporting `patch_to` which is decorated with `staticmethod`
  nbdev/doclinks.py
  nbs/api/doclinks.ipynb
Labels: bug

#1113 `exec_doc` supports re-rendering widgets
  nbdev/_modidx.py
  nbdev/processors.py
  nbs/api/processors.ipynb
Labels: enhancement

#1117 recursive defaults to `False` which excludes images and other sub-directories
  nbdev/config.py
  nbs/api/config.ipynb
Labels: bug

#1121 Enable Documentation Only Sites With `nbdev` ( + tutorial )
  nbdev/doclinks.py
  nbdev/quarto.py
  nbs/api/doclinks.ipynb
  nbs/api/quarto.ipynb
  nbs/tutorials/docs_only.ipynb
Labels: enhancement

#1129 `nbdev_new` defaults bool parameters to `False` (e.g. `put_version_in_init`)
  nbdev/config.py
  nbs/api/config.ipynb
Labels: bug

#1122 `black_formatting` setting is ignored
  nbdev/export.py
  nbs/api/export.ipynb
Labels: bug
