Repository AnswerDotAI/nbdev, pull requests merged in 2025-02, with the labels that each got.

#1496 fix: update workflow paths from fastai to answerdotai
  .github/workflows/deploy.yaml
  .github/workflows/test.yaml
  nbdev/cli.py
  nbs/api/13_cli.ipynb
Labels: bug

#1484 Support for Quarto 1.6 _brand.yml
  nbdev/serve.py
  nbs/api/17_serve.ipynb
  nbs/explanations/docs.ipynb
Labels: enhancement

#1500 Add Deprecation Warning For Conda
  nbdev/release.py
  nbs/api/18_release.ipynb
Labels: documentation
